version: "3.4"

services:
  db:
    image: "postgres:14.1-alpine"
    container_name: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: holoweb
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .data/db/:/var/lib/postgresql/data
    restart: always
    ports:
      - '5432:5432'
    networks:
      - backend

  redis:
    image: 'redis:6.2-alpine'
    container_name: 'redis'
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - .data/redis/:/data
    restart: always
    ports:
      - '6379:6379'
    networks:
      - backend

  app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge
